import { Prompt } from '../../types';

export const STARTER_PROMPTS: Prompt[] = [
  {
    id: 'starter-blog',
    name: 'Blog Post Outline & Generator',
    description: 'Write a well-structured blog post with engaging introduction, headings, and conclusion.',
    category: 'Writing',
    template: 'Write a well-structured blog post about [TOPIC] for [AUDIENCE]. Use an engaging introduction, clear headings, practical examples, and a concise conclusion.',
    variables: ['TOPIC', 'AUDIENCE'],
    tags: ['Blog', 'SEO', 'Long-form'],
    exampleUse: 'Topic: Impact of remote work on productivity | Audience: Business Managers',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-email',
    name: 'Professional Business Email',
    description: 'Write a polite, structured business email to a colleague or client.',
    category: 'Business',
    template: 'Write a professional email about [TOPIC] to [RECIPIENT]. Keep the tone [TONE] and make the message clear, polite, and action-oriented.',
    variables: ['TOPIC', 'RECIPIENT', 'TONE'],
    tags: ['Email', 'Communication', 'Business'],
    exampleUse: 'Topic: Project deadline extension request | Recipient: Project Sponsor | Tone: Professional',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-social',
    name: 'Engaging Social Media Post',
    description: 'Create social media posts optimized for specific platforms.',
    category: 'Social Media',
    template: 'Create an engaging social media post about [TOPIC] for [PLATFORM]. Keep it concise, attention-grabbing, include relevant hashtags, and target a [TONE] tone.',
    variables: ['TOPIC', 'PLATFORM', 'TONE'],
    tags: ['Social', 'Marketing', 'LinkedIn', 'Twitter'],
    exampleUse: 'Topic: Launching our new mobile app | Platform: LinkedIn | Tone: Excited & Professional',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-code',
    name: 'Algorithms & Code Generator',
    description: 'Create clean code solutions with explanations and complexity analysis.',
    category: 'Coding',
    template: 'Generate clean, readable [LANGUAGE] code that solves the following problem: [PROBLEM]. Explain the implementation, include comments where useful, and analyze the time complexity.',
    variables: ['LANGUAGE', 'PROBLEM'],
    tags: ['Development', 'Programming', 'Clean Code'],
    exampleUse: 'Language: TypeScript | Problem: Implementing a binary search tree search function',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-product',
    name: 'SaaS Product Description',
    description: 'Draft compelling marketing copy describing product features and benefits.',
    category: 'Marketing',
    template: 'Write a compelling product description for [PRODUCT_NAME]. Highlight its key features ([FEATURES]), main benefits ([BENEFITS]), and target customers ([TARGET_AUDIENCE]).',
    variables: ['PRODUCT_NAME', 'FEATURES', 'BENEFITS', 'TARGET_AUDIENCE'],
    tags: ['E-Commerce', 'Product', 'SaaS'],
    exampleUse: 'Product Name: TimeFlow | Features: Automated scheduling, calendar sync | Benefits: Saves 5 hours weekly | Target Audience: Freelancers',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-summary',
    name: 'Executive Summary Maker',
    description: 'Synthesize complex texts or reports into high-impact highlights.',
    category: 'Productivity',
    template: 'Summarize the following text or topic: [TEXT_OR_TOPIC]. Highlight the top 3 key takeaways, make it concise, and structure it for [AUDIENCE].',
    variables: ['TEXT_OR_TOPIC', 'AUDIENCE'],
    tags: ['Summarization', 'Reporting', 'Executive'],
    exampleUse: 'Text/Topic: Q2 financial reports showing 10% drop in retail but 40% growth in online | Audience: Executive Board',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-outreach',
    name: 'Cold Sales Pitch',
    description: 'Draft outreach messages that grab attention and address recipient pain points.',
    category: 'Marketing',
    template: 'Write a cold outreach message to [RECIPIENT_NAME] who is a [RECIPIENT_ROLE] at [COMPANY]. Pitch our service [SERVICE_NAME] which helps with [PAIN_POINT].',
    variables: ['RECIPIENT_NAME', 'RECIPIENT_ROLE', 'COMPANY', 'SERVICE_NAME', 'PAIN_POINT'],
    tags: ['Sales', 'Outreach', 'B2B'],
    exampleUse: 'Recipient: Sarah | Role: Head of HR | Company: TechGlobal | Service: AutoHire | Pain Point: Resume screening overload',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-interview',
    name: 'Interview Prep Generator',
    description: 'Get job-specific behavior and technical questions and ideal answer outlines.',
    category: 'Career',
    template: 'Create a list of [NUMBER_OF_QUESTIONS] technical and behavioral interview questions for a [JOB_TITLE] position. Include brief outlines of ideal answers for each.',
    variables: ['NUMBER_OF_QUESTIONS', 'JOB_TITLE'],
    tags: ['Interview', 'Hiring', 'Preparation'],
    exampleUse: 'Number of Questions: 5 | Job Title: Senior Frontend React Developer',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-seo',
    name: 'SEO Meta Tags Creator',
    description: 'Build search engine title and description tags targeting top keywords.',
    category: 'Marketing',
    template: 'Generate optimized SEO Title and Meta Description tags for a webpage about [PAGE_TOPIC]. Target the primary keywords: [KEYWORDS] and ensure length limits are respected.',
    variables: ['PAGE_TOPIC', 'KEYWORDS'],
    tags: ['SEO', 'Google Search', 'Metadata'],
    exampleUse: 'Page Topic: Budget gardening tools shop | Keywords: cheap garden tools, durable rakes, trowels',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-newsletter',
    name: 'Newsletter Copy Draft',
    description: 'Create custom emails for product announcements and weekly broadcasts.',
    category: 'Writing',
    template: 'Draft a newsletter broadcast for our subscribers about [TOPIC]. Include an attention-grabbing subject line, a friendly greeting, the main value proposition, and a clear Call To Action ([CTA]).',
    variables: ['TOPIC', 'CTA'],
    tags: ['Newsletter', 'Retention', 'Copywriting'],
    exampleUse: 'Topic: Introducing seasonal discounts | CTA: Shop 20% Off Now',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-outline',
    name: 'Academic Essay Outline',
    description: 'Construct logical outlines for educational research papers and reports.',
    category: 'Education',
    template: 'Develop a detailed outline for a research essay on [TOPIC]. Structure it with an introduction, body paragraphs focusing on key themes ([THEMES]), and a conclusion. Include thesis statement advice.',
    variables: ['TOPIC', 'THEMES'],
    tags: ['Education', 'Research', 'Essay'],
    exampleUse: 'Topic: The ethical implications of gene editing | Themes: Human enhancement, health equity, regulation',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-coverletter',
    name: 'Sleek Cover Letter Builder',
    description: 'Draft job-specific application letters demonstrating alignment.',
    category: 'Career',
    template: 'Write a personalized cover letter for the [JOB_TITLE] role at [COMPANY]. Emphasize my experience in [SKILLS] and keep the tone professional yet enthusiastic.',
    variables: ['JOB_TITLE', 'COMPANY', 'SKILLS'],
    tags: ['Career', 'Resume', 'Job Hunt'],
    exampleUse: 'Job Title: Data Analyst | Company: InnovateCorp | Skills: Python, SQL, Tableau dashboards',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-faq',
    name: 'FAQ Section Builder',
    description: 'Create common user questions and clear, helpful responses.',
    category: 'Business',
    template: 'Generate a list of 5 frequently asked questions and answers for a business specializing in [BUSINESS_TYPE]. The target audience is [AUDIENCE].',
    variables: ['BUSINESS_TYPE', 'AUDIENCE'],
    tags: ['FAQ', 'Support', 'Customer Service'],
    exampleUse: 'Business Type: Eco-friendly subscription coffee boxes | Audience: Environmentally-conscious coffee enthusiasts',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-grammar',
    name: 'Grammar & Style Enhancer',
    description: 'Revise user text blocks to refine language, clarity, and precision.',
    category: 'Productivity',
    template: 'Revise the following text to improve clarity, flow, and impact: [TEXT]. Maintain a [TONE] tone and ensure correct grammar.',
    variables: ['TEXT', 'TONE'],
    tags: ['Editor', 'Proofreading', 'Polishing'],
    exampleUse: 'Text: We gotta move fast on this deal else the competitors will take it. | Tone: Professional & Urgent',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-youtube',
    name: 'YouTube Script Outline',
    description: 'Outline video structure and write high-retention hooks.',
    category: 'Social Media',
    template: 'Create a video outline and hook script for a YouTube video about [VIDEO_TOPIC]. The target audience is [AUDIENCE] and the style should be [TONE].',
    variables: ['VIDEO_TOPIC', 'AUDIENCE', 'TONE'],
    tags: ['Video', 'YouTube', 'Creative'],
    exampleUse: 'Video Topic: 5 habits that save 2 hours daily | Audience: Busy professionals | Tone: Energetic & Educational',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-hook',
    name: 'Story Hook & Openers',
    description: 'Generate hooks that draw readers into creative writing projects.',
    category: 'Writing',
    template: 'Write 3 different engaging opening hooks for a story in the [GENRE] genre, featuring a protagonist who is [PROTAGONIST_DESC] facing the conflict: [CONFLICT].',
    variables: ['GENRE', 'PROTAGONIST_DESC', 'CONFLICT'],
    tags: ['Creative', 'Hooks', 'Fiction'],
    exampleUse: 'Genre: Cyberpunk | Protagonist: A rogue database cleaner | Conflict: Finding a deleted file containing human souls',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-adcopy',
    name: 'Varied Ad Copy Builder',
    description: 'Draft advertising copy variants highlighting hooks and features.',
    category: 'Marketing',
    template: 'Create 3 variations of advertising copy for [PRODUCT_NAME]. Each variation should target a different hook (e.g. pain point, curiosity, feature-led) and end with a CTA [CTA].',
    variables: ['PRODUCT_NAME', 'CTA'],
    tags: ['Ads', 'Copywriting', 'Conversion'],
    exampleUse: 'Product Name: SleepEasy Melatonin Gummies | CTA: Claim Your Free Sample Today',
    isFavorite: false,
    isCustom: false
  },
  {
    id: 'starter-slogan',
    name: 'Brand Slogan Generator',
    description: 'Generate catchy taglines that summarize brand core values.',
    category: 'Marketing',
    template: 'Generate 10 catchy slogans for a brand named [BRAND_NAME] which sells [PRODUCT_OR_SERVICE] and represents the values: [CORE_VALUES].',
    variables: ['BRAND_NAME', 'PRODUCT_OR_SERVICE', 'CORE_VALUES'],
    tags: ['Branding', 'Slogans', 'Creativity'],
    exampleUse: 'Brand Name: Solis | Product/Service: Solar roofing | Core Values: Clean energy, durability, affordability',
    isFavorite: false,
    isCustom: false
  }
];
